version: "3.8"
services:
  mysql:
    image: mysql:8.0
    container_name: glow_mysql
    restart: unless-stopped
    ports:
      - "3307:3306"
    # env_file:           # <- comment out while testing if you want
    #  - .env
    environment:
      MYSQL_ROOT_PASSWORD: "Ra123@123@123@"
      MYSQL_DATABASE: glow_services
      MYSQL_ROOT_HOST: "%"
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  mysql-data: